full_django_blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from myblog import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls')),
    path('account/', include('allauth.urls')),

]
# Necessary shit !
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

full_django_blog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include, reverse

from .models import Post
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

from . import views
app_name = 'myblog'
urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('detail/<int:pk>/update', PostUpdateView.as_view(), name='update'),
    path('detail/new', PostCreateView.as_view(), name='create'),
    path('detail/<int:pk>/delete', PostDeleteView.as_view(), name='delete'),
    path('profile/', views.profile, name='profile')
]

# the template that it expects is just a form that ask are you sure to delete the post
# this template has a name 'post_confirm_delete'

full_django_blog/myblog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CharField)

    def get_absolute_url(self):
        return reverse('myblog:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_pics', default='profile_pics/download.png')

    def __str__(self):
        return f'{self.user} Profile'

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=User)

full_django_blog/myblog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', ]


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image']

full_django_blog/myblog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse

from .models import Post
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from .forms import UserProfileForm, UserUpdateForm
from .models import Profile
from django.contrib.auth.decorators import login_required


class PostListView(ListView):
    model = Post
    template_name = 'myblog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']


# @method_decorator(login_required, name='dispatch')
class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    # context is automatically called 'object'


class PostCreateView(LoginRequiredMixin, CreateView):  # context rendered is 'form'
    model = Post
    fields = ['title', 'content']

    # success_url = reverse_lazy('detail')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

# This view does'nt requires a template


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView, ):   # context rendered is 'form' , this order is toooo important
    model = Post
    fields = ['title', 'content']
    # success_url = reverse_lazy('detail')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    success_url = '/'

    def test_func(self):
        obj = self.get_object()
        if obj.author == self.request.user:
            return True
        else:
            raise Http404("You are not allowed to edit this Post")


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        obj = self.get_object()
        if obj.author == self.request.user:
            return True
        else:
            raise Http404("You are not allowed to delete this Post")


@login_required
def profile(request):
    template = 'account/profile.html'
    details = Profile.objects.get(user=request.user)
    if request.method == "POST":
        p_form = UserProfileForm(request.POST, request.FILES, instance=request.user.profile)
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'your profile has been updated !')
            return redirect('/profile')
    else:
        p_form = UserProfileForm(instance=request.user.profile)
        u_form = UserUpdateForm(instance=request.user)

    context = {'details': details,
               'u_form': u_form,
               'p_form': p_form}
    return render(request, template, context)

full_django_blog/myblog/templates/myblog/home.html
{% extends "base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            {% if post.author.profile.image.url %}
            <img class='rounded-circle article-img' src="{{ post.author.profile.image.url}}" alt="none">
            {% endif %}
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted| date:'F d, Y'}}</small>
            </div>
            <h2><a class="article-title" href="{% url 'myblog:detail' post.id %}">{{ post.title| title }}</a></h2> <!--# the post.id, the post word in this came from the for loop-->
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

full_django_blog/myblog/templates/myblog/post_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}" ?</h2>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'myblog:detail' object.id %}">Cancel</a>

            </div>
        </form>
{% endblock content %}

full_django_blog/myblog/templates/myblog/post_detail.html
{% extends "base.html" %}
{% block content %}

<article class="media content-section">
            <img class='rounded-circle article-img' src="{{ object.author.profile.image.url }}" alt="none">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ object.author }}</a>
              <small class="text-muted">{{ object.date_posted| date:'F d, Y'}}</small>
            </div>
            <h2 class="article-title" >{{ object.title| title }}</h2>
            <p class="article-content">{{ object.content }}</p>
          </div>
        </article>


{% endblock content %}

full_django_blog/myblog/templates/myblog/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
{% endblock content %}

full_django_blog/myblog/templates/myblog/thanks.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h>Thanks !</h>


{% endblock content %}

full_django_blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'myblog/main.css' %}">

    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'myblog:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'myblog:home' %}">Home</a>
              <a class="nav-item nav-link" href='#'>About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if not request.user.is_authenticated %}

          <a class="dropdown-item" href="{% url 'account_login'%}">Login</a>
          <a class="dropdown-item" href="{% url 'account_signup'%}">Signup</a>
          {% else %}
                <div class="navbar-brand"> Hello {{request.user}} !</div>
                <a class="dropdown-item" href="{% url 'myblog:profile'%}">Profile</a>
                <a class="dropdown-item" href="{% url 'account_logout'%}">Logout</a>
          {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}

            {% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>